// abilities.js

export const abilitaInfernali = [
  { nome: "Guida Infernale", descrizione: "Controllare veicoli demoniaci" },
  { nome: "Cucina Dannata", descrizione: "Preparare piatti con ingredienti infernali" },
  { nome: "Tecnologia Maledetta", descrizione: "Hackerare dispositivi posseduti" },
  { nome: "Burocrazia Infernale", descrizione: "Manipolare documenti di dannazione" },
  { nome: "Medicina Non Convenzionale", descrizione: "Curare con metodi alternativi" },
  { nome: "Nuoto Estremo", descrizione: "Sopravvivere in liquidi corrosivi" },
  { nome: "Riparazione Meccanica", descrizione: "Riparare armi e veicoli infernali" },
  { nome: "Lavoro Infernale", descrizione: "Operare in ambienti lavorativi demoniaci" },
  { nome: "Gestione Illecita", descrizione: "Gestire scambi e micro-crimini" },
  { nome: "Armi da Fuoco Leggere", descrizione: "Uso di pistole e revolver" },
  { nome: "Armi Pesanti", descrizione: "Uso di fucili e mitragliatrici infernali" },
  { nome: "Corpo a Corpo Urbano", descrizione: "Combattimento fisico ravvicinato" },
  { nome: "Parkour Infernale", descrizione: "Acrobazie tra strutture decadenti" },
  { nome: "Camuffamento Rapido", descrizione: "Cambiare aspetto in pochi istanti" },
  { nome: "Furtività Urbana", descrizione: "Muoversi senza essere visti" },
  { nome: "Tracciamento Urbano", descrizione: "Seguire creature in città infernali" },
  { nome: "Inganni e Trappole", descrizione: "Creare diversivi e trappole visive" },
  { nome: "Tempra Afrodisiaca", descrizione: "Resistenza e vigore in ambito intimo" },
  { nome: "Olfatto sopraffino", descrizione: "Sentire odori in modo superiore" },
  { nome: "Udito sopraffino", descrizione: "Percepire rumori impercettibili" },
  { nome: "Vista eccezionale", descrizione: "Osservare dettagli con precisione" },
  { nome: "Resistenza ad Alcol/Droghe", descrizione: "Sopportare e sfruttare sostanze" },
  { nome: "Scassinare", descrizione: "Aprire serrature e meccanismi" },
  { nome: "Cantare", descrizione: "Incantare con la voce" },
  { nome: "Conoscenza dei piani", descrizione: "Conoscenza dei piani infernali" }
];

export const abilitaCelestiali = [
  { nome: "Guida Celestiale", descrizione: "Condurre carri di luce o veicoli angelici" },
  { nome: "Cucina Benedetta", descrizione: "Preparare piatti con ingredienti puri e divini" },
  { nome: "Tecnologia Sacra", descrizione: "Usare e armonizzare strumenti celestiali" },
  { nome: "Burocrazia Angelica", descrizione: "Gestire registri e documenti delle anime" },
  { nome: "Medicina Miracolosa", descrizione: "Curare con energia luminosa e benedizioni" },
  { nome: "Nuoto di Luce", descrizione: "Muoversi in mari eterei o nuvole liquide" },
  { nome: "Riparazione Celestiale", descrizione: "Riparare strumenti sacri e reliquie" },
  { nome: "Lavoro Angelico", descrizione: "Operare in comunità celesti con dedizione" },
  { nome: "Gestione Armoniosa", descrizione: "Coordinare scambi e risorse in modo equo" },
  { nome: "Arti di Luce", descrizione: "Creare raggi, scudi e proiezioni luminose" },
  { nome: "Canto Corale", descrizione: "Elevare inni che rafforzano e ispirano" },
  { nome: "Corpo a Corpo Sacro", descrizione: "Difesa fisica con tecniche armoniose" },
  { nome: "Parkour Celestiale", descrizione: "Muoversi agilmente tra nuvole e templi" },
  { nome: "Trasfigurazione Rapida", descrizione: "Cambiare aspetto in forme angeliche" },
  { nome: "Presenza Silenziosa", descrizione: "Muoversi senza disturbare l’armonia" },
  { nome: "Tracciamento di Luce", descrizione: "Seguire tracce energetiche pure" },
  { nome: "Illusioni Luminose", descrizione: "Creare visioni rassicuranti o protettive" },
  { nome: "Tempra Radiosa", descrizione: "Resistenza spirituale e vigore interiore" },
  { nome: "Olfatto Purificato", descrizione: "Percepire fragranze eteree e simboliche" },
  { nome: "Udito Angelico", descrizione: "Ascoltare melodie e voci impercettibili" },
  { nome: "Vista Divina", descrizione: "Osservare dettagli e verità nascoste" },
  { nome: "Immunità Celestiale", descrizione: "Resistere a sostanze corruttrici o negative" },
  { nome: "Apertura Sacra", descrizione: "Sbloccare sigilli e porte divine" },
  { nome: "Voce Incantatrice", descrizione: "Incantare e ispirare con il canto" },
  { nome: "Conoscenza dei Regni", descrizione: "Sapienza dei piani celesti e cosmici" },
  { nome: "Volare", descrizione: "Saper usare le ali" }
];
